'''
'职位'名称清洗模块
比如：开发工程师8k薪资->开发工程师，软件开发工程师->开发工程师
可直接调用clean(df)函数，
自带读写csv函数 该模块也可以单独运行产生清洗好的csv文件。
作者：董礼业
'''
import pandas as pd


def read_file(filename):
    df = pd.read_csv(filename)
    print(df.shape)
    df.drop_duplicates(inplace=True) # 删除重复数据
    df.reset_index(drop=True,inplace=True) # 重新设置列标
    return df


def describe(df):
    print(df.shape)
    print(df.head(3))


def clean(df):
    df['职位']=df.职位.apply(lambda x:'CTO' if x.find('CTO')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'视频广告设计师' if x.find('视频')!=-1 and x.find('广告')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'游戏视频设计师' if x.find('视频')!=-1 and x.find('游戏')!=-1 and x.find('设计')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'视频特效设计师' if x.find('视频')!=-1 and x.find('特效')!=-1 and x.find('设计')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'视频设计师' if x.find('视频')!=-1 and x.find('设计')!=-1 and x.find('U')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'视频剪辑师' if x.find('视频')!=-1 and x.find('剪')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'视频编辑师' if x.find('抖音')==-1 and x.find('视频')!=-1 and x.find('编辑')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'视频制作师' if x.find('视频')!=-1 and x.find('制作')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'用户体验设计师' if x.find('体验')!=-1 and x.find('设计')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'用户(游戏)体验' if x.find('体验')!=-1 and x.find('设计')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'需求分析师' if x.find('需求')!=-1 else x)

    df['职位']=df.职位.apply(lambda x:'平面UI美工实习' if (x.find('美')!=-1 or x.find('UI')!=-1 or x.find('ui')!=-1 or x.find('平面')!=-1 )and(x.find('实习')!=-1 or x.find('学徒')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'平面设计师' if x.find('平面')!=-1 and x.find('设计')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'视觉设计总监' if x.find('视觉')!=-1 and x.find('设计')!=-1 and(x.find('主管')!=-1 or x.find('经理')!=-1 or x.find('总监')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'视觉设计师' if x.find('视觉')!=-1 and x.find('设计')!=-1 and x.find('总监')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'电商美工' if (x.find('美')!=-1 or x.find('UI')!=-1 or x.find('ui')!=-1)and(x.find('电商')!=-1 or x.find('淘宝')!=-1 or x.find('天猫')!=-1 or x.find('阿里')!=-1 or x.find('京东')!=-1 or x.find('唯品会')!=-1 or x.find('亚马逊')!=-1 or x.find('网店')!=-1 or x.find('电子商务')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'网页UI设计师' if (x.find('美')!=-1 or x.find('UI')!=-1 or x.find('ui')!=-1)and(x.find('网')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'网页设计师' if x.find('网页UI设计师')==-1 and(x.find('eb')!=-1 or x.find('EB')!=-1 or x.find('网页')!=-1)and x.find('设计')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网页制作' if x.find('网页')!=-1 and x.find('制作')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网页测试' if x.find('网页')!=-1 and x.find('测试')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'游戏UI设计师' if (x.find('美')!=-1 or x.find('UI')!=-1 or x.find('ui')!=-1 or x.find('平面')!=-1)and(x.find('游戏')!=-1 or x.find('手游')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'UI设计师' if (x.find('美')!=-1 or x.find('UI')!=-1 or x.find('ui')!=-1 or x.find('平面')!=-1)and(x.find('设计')!=-1 or x.find('工程')!=-1)and x.find('游戏')==-1 and x.find('网')==-1 and x.find('电商')==-1 and x.find('实习')==-1 and x.find('平面设计师')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'美工' if x.find('美工')!=-1 and x.find('电商')==-1 and x.find('实习')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'视觉设计师' if x.find('视觉')!=-1 and x.find('设计')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'文案编辑' if x.find('编辑')!=-1 or x.find('主编')!=-1 or x.find('文章')!=-1 or x.find('文员')!=-1 or x.find('写手')!=-1 or x.find('文职')!=-1 or x.find('文案')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'项目经理' if x.find('项目经理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'经理助理' if x.find('经理助理')!=-1 else x)

    df['职位']=df.职位.apply(lambda x:'销售主管' if x.find('销售')!=-1 and(x.find('经理')!=-1 or x.find('主管')!=-1 or x.find('总监')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'销售代表' if x.find('销售')!=-1 and x.find('代表')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'销售实习' if x.find('销售')!=-1 and x.find('实习')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'销售客服' if x.find('销售')!=-1 and x.find('客服')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'销售专员' if x.find('销售')!=-1 and x.find('客服')==-1 and x.find('实习')==-1 and x.find('代表')==-1 and x.find('主管')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'采购专员' if x.find('采购')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'推广专员' if x.find('推广')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'产品专家' if x.find('产品专家')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'产品策划师' if x.find('产品')!=-1 and(x.find('设计')!=-1 or x.find('策划')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'产品引入' if x.find('产品')!=-1 and(x.find('引入')!=-1 or x.find('调研')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'产品测试' if x.find('产品')!=-1 and(x.find('测试')!=-1 or x.find('质检')!=-1 or x.find('验证')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'产品开发' if x.find('产品')!=-1 and(x.find('开发')!=-1 or x.find('研发')!=-1 or x.find('技术')!=-1 or x.find('实习')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'产品助理' if x.find('产品助理')!=-1 or x.find('产品专员')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'产品经理' if x.find('产品')!=-1 and(x.find('经理')!=-1 or x.find('主管')!=-1 or x.find('负责')!=-1 or x.find('总监')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'产品运营' if x.find('产品')!=-1 and x.find('运营')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'产品测评' if x.find('产品')!=-1 and x.find('测评')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'产品运维' if x.find('产品')!=-1 and x.find('运维')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'产品分析' if x.find('产品')!=-1 and x.find('分析')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'产品工程师' if x.find('产品')!=-1 and x.find('工程师')!=-1 else x)

    df['职位']=df.职位.apply(lambda x:'Linux运维工程师' if x.find('inux')!=-1 and x.find('运维')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Linux测试工程师' if x.find('inux')!=-1 and x.find('测试')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Linux嵌入式开发工程师' if x.find('inux')!=-1 and x.find('嵌入式')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Linux系统工程师' if x.find('inux')!=-1 and x.find('系统')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Linux内核开发工程师' if x.find('inux')!=-1 and x.find('内核')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Linux驱动开发工程师' if x.find('inux')!=-1 and(x.find('驱动')!=-1 or x.find('rive')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'Linux开发工程师' if x.find('inux')!=-1 and x.find('运维')==-1 and x.find('测试')==-1 and x.find('嵌入式')==-1 and x.find('系统')==-1 and x.find('内核')==-1 and x.find('驱动')==-1 else x)

    df['职位']=df.职位.apply(lambda x:'Web开发主管' if (x.find('web')!=-1 or x.find('Web')!=-1 or x.find('WEB')!=-1 or x.find('网页')!=-1)and(x.find('经理')!=-1 or x.find('主管')!=-1 or x.find('总监')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'Web测试工程师' if (x.find('web')!=-1 or x.find('Web')!=-1 or x.find('WEB')!=-1)and x.find('测试')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Web后端开发' if (x.find('web')!=-1 or x.find('Web')!=-1 or x.find('WEB')!=-1)and x.find('后')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Web前端开发实习' if (x.find('web')!=-1 or x.find('Web')!=-1 or x.find('WEB')!=-1)and x.find('前')!=-1 and x.find('实习')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Web架构师' if (x.find('web')!=-1 or x.find('Web')!=-1 or x.find('WEB')!=-1)and x.find('架')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Web全栈工程师' if (x.find('web')!=-1 or x.find('Web')!=-1 or x.find('WEB')!=-1)and x.find('栈')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Web研发工程师' if (x.find('web')!=-1 or x.find('Web')!=-1 or x.find('WEB')!=-1)and x.find('研')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Web前端开发工程师' if (x.find('web')!=-1 or x.find('Web')!=-1 or x.find('WEB')!=-1 or x.find('网页')!=-1)and x.find('前')!=-1 and x.find('实习')==-1 and x.find('架构')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java_web开发工程师' if (x.find('web')!=-1 or x.find('Web')!=-1 or x.find('WEB')!=-1)and(x.find('ava')!=-1 or x.find('AVA')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'WebAPP开发工程师' if (x.find('web')!=-1 or x.find('Web')!=-1 or x.find('WEB')!=-1)and(x.find('pp')!=-1 or x.find('PP')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'Web安全工程师' if (x.find('web')!=-1 or x.find('Web')!=-1 or x.find('WEB')!=-1)and x.find('安全')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Web开发工程师' if (x.find('web')!=-1 or x.find('Web')!=-1 or x.find('WEB')!=-1 or x.find('网页')!=-1)and(x.find('开发')!=-1 or x.find('工程')!=-1)and x.find('Web前端开发工程师')==-1 
    and x.find('研发')==-1 and x.find('安全')==-1 and x.find('全栈')==-1 and x.find('测试')==-1 and x.find('实习')==-1 and x.find('ava')==-1 and x.find('主管')==-1 and x.find('后端')==-1 and x.find('APP')==-1 else x)

    df['职位']=df.职位.apply(lambda x:'Javascript开发工程师' if x.find('ava')!=-1 and x.find('cript')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'J2EE企业级开发' if x.find('J2EE')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'区块链工程师' if x.find('区块链')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'爬虫工程师' if x.find('爬虫')!=-1 or x.find('抓取')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Hadoop工程师' if x.find('adoop')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'数据库工程师' if x.find('数据库')!=-1 or x.find('Oracle')!=-1 or x.find('数据管理')!=-1 or x.find('sql')!=-1 or x.find('SQL')!=-1 or x.find('DB')!=-1 or x.find('db')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'golang开发工程师' if x.find('oogle')==-1 and (x.find('go')!=-1 or x.find('Go')!=-1) else x)

    df['职位']=df.职位.apply(lambda x:'Java安全工程师' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('安全')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java大数据' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('数据')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java全栈工程师' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('栈')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java开发助理' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('助理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java技术经理' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('经理')!=-1 and x.find('技术')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java开发经理' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('经理')!=-1 and x.find('开发')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java研发经理' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('研发')!=-1 and(x.find('经理')!=-1 or x.find('总监')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'Java开发主管' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('主管')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java架构师' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('架构')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java研发工程师' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('研发')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java运维工程师' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('维')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java游戏服务器开发' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('服务')!=-1 and x.find('游戏')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java服务器开发' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('服务')!=-1 and x.find('游戏')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java开发实习生' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and(x.find('实习')!=-1 or x.find('实训')!=-1 or x.find('学徒')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'Java后台开发' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('后')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java讲师' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('讲')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java技术顾问' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('顾问')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java测试工程师' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('测试')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java游戏开发' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('游')!=-1 and x.find('服务器')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java软件工程师' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and x.find('软件')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Java开发工程师' if (x.find('ava')!=-1 or x.find('AVA')!=-1)and(x.find('开发')!=-1 or x.find('程序')!=-1 or x.find('工程')!=-1)and x.find('研发')==-1 and x.find('数据')==-1 and x.find('栈')==-1 and x.find('运维')==-1 
    and x.find('测试')==-1 and x.find('安全')==-1 and x.find('软件')==-1 and x.find('理')==-1 and x.find('管')==-1 and x.find('游')==-1 and x.find('服')==-1 and x.find('实')==-1 and x.find('后')==-1 and x.find('web')==-1 and x.find('script')==-1 else x)

    df['职位']=df.职位.apply(lambda x:'PHP开发实习生' if (x.find('php')!=-1 or x.find('PHP')!=-1)and x.find('实习')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'PHP开发主管' if (x.find('php')!=-1 or x.find('PHP')!=-1)and(x.find('经理')!=-1 or x.find('主管')!=-1 or x.find('总监')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'PHP后端开发' if (x.find('php')!=-1 or x.find('PHP')!=-1)and x.find('后')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'PHP架构师' if (x.find('php')!=-1 or x.find('PHP')!=-1)and x.find('架构')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'PHP研发' if (x.find('php')!=-1 or x.find('PHP')!=-1)and x.find('研发')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'PHP服务器开发' if (x.find('php')!=-1 or x.find('PHP')!=-1)and x.find('服务器')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'PHP全栈开发' if (x.find('php')!=-1 or x.find('PHP')!=-1)and x.find('栈')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'PHP开发助理' if (x.find('php')!=-1 or x.find('PHP')!=-1)and x.find('助理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'PHP开发工程师' if (x.find('php')!=-1 or x.find('PHP')!=-1)and(x.find('工程')!=-1 or x.find('开发')!=-1 or x.find('程序')!=-1)and x.find('实习')==-1 and x.find('主管')==-1 and x.find('后端')==-1 and x.find('服务器')==-1 and x.find('全栈')==-1 and x.find('助理')==-1 else x)

    df['职位']=df.职位.apply(lambda x:'网站运营实习生' if x.find('网站')!=-1 and x.find('实习')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网站运营助理' if x.find('网站')!=-1 and x.find('助理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网站客服' if x.find('网站')!=-1 and x.find('客服')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网站设计师' if x.find('网站')!=-1 and x.find('设计')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网站策划' if x.find('网站')!=-1 and x.find('策划')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网站运维' if x.find('网站')!=-1 and x.find('维')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网站SEO' if x.find('网站')!=-1 and x.find('SEO')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网站建设' if x.find('网站')!=-1 and x.find('建设')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网站优化' if x.find('网站')!=-1 and x.find('优化')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网站运营经理' if x.find('网站')!=-1 and(x.find('经理')!=-1 or x.find('总监')!=-1 or x.find('主管')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'网站开发工程师' if x.find('网站')!=-1 and(x.find('程序')!=-1 or x.find('开发')!=-1 or x.find('工程')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'网站运营专员' if x.find('网站')!=-1 and x.find('运营')!=-1 and x.find('理')==-1 and x.find('实习')==-1 else x)

    df['职位']=df.职位.apply(lambda x:'数据挖掘工程师' if x.find('数据')!=-1 and x.find('挖掘')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'NLP' if x.find('NLP')!=-1 or x.find('语义')!=-1 or x.find('自然语言')!=-1 or x.find('智能语言')!=-1else x)
    df['职位']=df.职位.apply(lambda x:'图像算法' if x.find('图像')!=-1 or x.find('点云')!=-1 or x.find('OCR')!=-1 or x.find('ocr')!=-1 or x.find('光学')!=-1 or x.find('三维图形')!=-1 or x.find('三维重建')!=-1 or x.find('图形算法')!=-1 or x.find('图算法')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'机器视觉算法' if x.find('视觉')!=-1 and(x.find('算法')!=-1 or x.find('机')!=-1 or x.find('工程')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'语音识别' if x.find('语音')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'推荐算法' if x.find('推荐')!=-1 or x.find('投放算法')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'机器学习实习生' if x.find('机器学习')!=-1 and x.find('实习')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'机器学习算法' if x.find('机器学习')!=-1 and x.find('算法')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'机器学习研发' if x.find('机器学习')!=-1 and x.find('研发')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'机器人算法' if x.find('机器人')!=-1 and x.find('算法')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'智能机器人开发' if x.find('机器人')!=-1 and(x.find('开发')!=-1 or x.find('')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'乐高机器人老师' if x.find('机器人')!=-1 and x.find('乐高')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'AI实习' if (x.find('人工智能')!=-1 or x.find('AI')!=-1)and(x.find('实习')!=-1 or x.find('实训')!=-1 or x.find('学徒')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'AI训练师' if x.find('人工智能')!=-1 and x.find('训练')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'AI产品经理' if (x.find('人工智能')!=-1 or x.find('AI')!=-1)and(x.find('产品')!=-1 or x.find('经理')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'AI系统工程师' if x.find('AI')!=-1 and x.find('系统')!=-1 and x.find('AIX')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'AI测试工程师' if x.find('AI')!=-1 and x.find('测试')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'AI算法' if (x.find('人工智能')!=-1 or x.find('AI')!=-1)and x.find('算法')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'AI应用实施' if x.find('AI')!=-1 and(x.find('实施')!=-1 or x.find('应用')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'AI工程师' if (x.find('人工智能')!=-1 or x.find('AI')!=-1)and(x.find('工程')!=-1 or x.find('开发')!=-1 or x.find('eader')!=-1 or x.find('研发')!=-1 or x.find('rogrammer')!=-1 or x.find('技术')!=-1 or x.find('科学')!=-1)and x.find('应用')==-1 and x.find('算法')==-1 and x.find('系统')==-1 and x.find('测试')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'深度学习实习生' if x.find('深度学习')!=-1 and x.find('实习')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'深度学习算法' if x.find('深度学习')!=-1 and x.find('工程')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'模型算法' if x.find('算法')!=-1 and x.find('模型')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'音视频算法' if x.find('算法')!=-1 and(x.find('视频')!=-1 or x.find('音')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'定位算法' if x.find('算法')!=-1 and x.find('定位')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'算法实习生' if x.find('算法')!=-1 and x.find('实习')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'算法技术总监' if x.find('算法')!=-1 and(x.find('总监')!=-1 or x.find('leader')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'嵌入式算法' if x.find('算法')!=-1 and(x.find('嵌入式')!=-1 or x.find('FPGA')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'大数据算法' if x.find('算法')!=-1 and x.find('数据')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网络算法' if x.find('算法')!=-1 and x.find('网络')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'信号处理算法' if x.find('算法')!=-1 and x.find('信号')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'C++算法' if x.find('算法')!=-1 and x.find('C++')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'算法优化' if x.find('算法')!=-1 and x.find('优化')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'控制算法' if x.find('算法')!=-1 and x.find('控制')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'算法负责人' if x.find('算法')!=-1 and x.find('负责')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'算法研发' if x.find('算法')!=-1 and (x.find('研')!=-1 or x.find('发')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'算法设计' if x.find('算法')!=-1 and x.find('设计')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'算法专家' if x.find('算法')!=-1 and x.find('专家')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'算法工程师' if x.find('算法')!=-1 and x.find('工程')!=-1 else x)

    df['职位']=df.职位.apply(lambda x:'数据分析主管' if x.find('数据')!=-1 and x.find('分析')!=-1 and(x.find('主管')!=-1 or x.find('经理')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'数据分析与运营' if x.find('数据')!=-1 and x.find('分析')!=-1 and x.find('运营')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'数据运营经理' if x.find('数据运营')!=-1 and x.find('经理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'数据分析专员' if x.find('数据分析')!=-1 and x.find('员')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'数据分析助理' if x.find('数据')!=-1 and x.find('分析')!=-1 and x.find('助理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'数据运营专家' if x.find('数据运营专家')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'大数据运维' if x.find('数据')!=-1 and x.find('维')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'大数据实习' if x.find('数据')!=-1 and (x.find('实习')!=-1 or x.find('实训')!=-1 or x.find('学徒')!=-1) else x)
    df['职位']=df.职位.apply(lambda x:'大数据实施工程师' if x.find('数据')!=-1 and x.find('实施')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'大数据架构师' if x.find('数据')!=-1 and x.find('架构')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'数据标注' if x.find('数据')!=-1 and x.find('标注')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'数据统计专员' if x.find('数据')!=-1 and(x.find('统计')!=-1 or x.find('采集')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'数据建模' if x.find('数据')!=-1 and x.find('模')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'数据处理' if x.find('数据')!=-1 and x.find('处理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'金融大数据' if x.find('数据')!=-1 and x.find('金融')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'数据仓库工程师' if x.find('数据')!=-1 and x.find('仓')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'大数据研发工程师' if x.find('数据')!=-1 and x.find('研发')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'大数据开发工程师' if x.find('数据')!=-1 and x.find('开发')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'大数据应用' if x.find('数据')!=-1 and x.find('应用')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'数据中心操作员' if x.find('数据中心')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'GIS数据工程师' if x.find('数据')!=-1 and x.find('GIS')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'数据可视化工程师' if x.find('数据')!=-1 and x.find('可视化')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'大数据分析师' if x.find('数据')!=-1 and(x.find('分析')!=-1 or x.find('治理')!=-1)and x.find('专员')==-1 and x.find('主管')==-1 and x.find('助理')==-1 and x.find('运营')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'大数据工程师' if x.find('数据')!=-1 and x.find('工程')!=-1 and x.find('库')==-1 and x.find('大数据开发')==-1 and x.find('挖掘')==-1 and x.find('研发')==-1 and x.find('可视化')==-1 and x.find('实施')==-1 and x.find('GIS')==-1 else x)

    df['职位']=df.职位.apply(lambda x:'Python开发实习' if x.find('ython')!=-1 and x.find('实习')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Python后端开发' if x.find('ython')!=-1 and x.find('后')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Python开发助理' if x.find('ython')!=-1 and x.find('助理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Python网络安全工程师' if x.find('ython')!=-1 and x.find('网络')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Python讲师' if x.find('ython')!=-1 and x.find('讲师')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Python讲师' if x.find('ython')!=-1 and x.find('实习')==-1 and x.find('后端')==-1 and x.find('助理')==-1 and x.find('经理')==-1 and x.find('安全')==-1 and x.find('讲师')==-1 and x.find('测试')==-1 else x)

    df['职位']=df.职位.apply(lambda x:'C#软件测试' if x.find('C#')!=-1 and x.find('测试')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'C#.NET实习' if (x.find('net')!=-1 or x.find('NET')!=-1 or x.find('c#')!=-1 or x.find('C#')!=-1)and x.find('实习')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'C#.NET研发' if (x.find('net')!=-1 or x.find('NET')!=-1 or x.find('c#')!=-1 or x.find('C#')!=-1)and x.find('研发')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'C#.NET开发主管' if (x.find('net')!=-1 or x.find('NET')!=-1 or x.find('c#')!=-1)and(x.find('主管')!=-1 or x.find('经理')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'C#.NET架构师' if (x.find('net')!=-1 or x.find('NET')!=-1 or x.find('C#')!=-1)and x.find('架构')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'.NET实施工程师' if x.find('net')!=-1 and x.find('实施')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'.NET讲师' if x.find('net')!=-1 and x.find('讲师')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'C#游戏服务端开发' if x.find('C#')!=-1 and x.find('游戏')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'C#.NET开发工程师' if (x.find('net')!=-1 or x.find('NET')!=-1 or x.find('c#')!=-1 or x.find('C#')!=-1)and x.find('测试')==-1 and x.find('实习')==-1 and x.find('研发')==-1 and x.find('主管')==-1 and x.find('架构')==-1 and x.find('实施')==-1 and x.find('讲师')==-1 and x.find('服务')==-1 else x)

    df['职位']=df.职位.apply(lambda x:'Android开发实习生' if x.find('Android')!=-1 and x.find('实习')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Android开发主管' if x.find('Android')!=-1 and(x.find('主管')!=-1 or x.find('经理')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'Android研发' if x.find('Android')!=-1 and x.find('研发')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Android系统开发' if x.find('ndroid')!=-1 and x.find('系统')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Android架构师' if x.find('Android')!=-1 and x.find('架构')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Android驱动工程师' if x.find('ndroid')!=-1 and x.find('驱动')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Android_SDK工程师' if x.find('ndroid')!=-1 and(x.find('sdk')!=-1 or x.find('SDK')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'Android测试工程师' if x.find('ndroid')!=-1 and x.find('测试')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Android逆向开发' if x.find('ndroid')!=-1 and x.find('逆向')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Android/iOS开发' if x.find('ndroid')!=-1 and x.find('iOS')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Android开发工程师' if x.find('ndroid')!=-1 and x.find('实习')==-1 and x.find('主管')==-1 and x.find('研发')==-1 and x.find('系统')==-1 and x.find('架构')==-1 and x.find('驱动')==-1 and x.find('SDK')==-1 and x.find('测试')==-1 and x.find('逆向')==-1 and x.find('讲师')==-1 and x.find('iOS')==-1 else x)

    df['职位']=df.职位.apply(lambda x:'iOS开发实习生' if (x.find('iOS')!=-1 or x.find('IOS')!=-1)and x.find('实习')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'iOS开发主管' if x.find('iOS')!=-1 and x.find('主管')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'iOS研发' if (x.find('iOS')!=-1 or x.find('IOS')!=-1 or x.find('ios')!=-1)and x.find('研发')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'iOS架构' if x.find('iOS')!=-1 and x.find('架构')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'iOS_SDK开发' if (x.find('iOS')!=-1 or x.find('IOS')!=-1)and x.find('SDK')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'iOS开发工程师' if (x.find('iOS')!=-1 or x.find('IOS')!=-1 or x.find('ios')!=-1)and x.find('实习')==-1 and x.find('主管')==-1 and x.find('研发')==-1 and x.find('架构')==-1 and x.find('SDK')==-1 and x.find('测试')==-1 and x.find('安全')==-1 and x.find('ndroid')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'Node.js开发工程师' if x.find('ode')!=-1 and(x.find('js')!=-1 or x.find('JS')!=-1 or x.find('Js')!=-1)else x)

    df['职位']=df.职位.apply(lambda x:'网络主播' if x.find('主播')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'游戏客服' if (x.find('游戏')!=-1 or x.find('手游')!=-1)and x.find('客服')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'游戏音效' if (x.find('游戏')!=-1 or x.find('手游')!=-1)and x.find('音效')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'游戏特效' if (x.find('游戏')!=-1 or x.find('手游')!=-1)and x.find('特效')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'游戏动作设计师' if x.find('游戏动作')!=-1 or x.find('动作设计')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'游戏策划师' if (x.find('游戏')!=-1 or x.find('手游')!=-1)and x.find('策划')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'游戏测试' if (x.find('游戏')!=-1 or x.find('手游')!=-1)and x.find('测试')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'游戏设计' if (x.find('游戏')!=-1 or x.find('手游')!=-1)and x.find('设计')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'游戏评测' if (x.find('游戏')!=-1 or x.find('手游')!=-1)and(x.find('评测')!=-1 or x.find('试玩')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'cocos2d游戏开发' if x.find('cocos')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'游戏服务端开发' if (x.find('游戏')!=-1 or x.find('手游')!=-1)and(x.find('服务')!=-1 or x.find('后端')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'游戏客户端开发' if (x.find('游戏')!=-1 or x.find('手游')!=-1)and x.find('客户端')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'游戏运维' if (x.find('游戏')!=-1 or x.find('手游')!=-1)and x.find('运维')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'游戏广告设计优化' if (x.find('游戏')!=-1 or x.find('手游')!=-1)and x.find('广告')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'游戏代练' if x.find('代练')!=-1 or x.find('陪练')!=-1 or x.find('代玩')!=-1 or x.find('带玩')!=-1 or((x.find('游戏')!=-1 or x.find('手游')!=-1)and x.find('打')!=-1 or x.find('操作')!=-1 or x.find('爱好')!=-1 or x.find('喜欢')!=-1 or x.find('玩')!=-1 or x.find('精英')!=-1 or x.find('大佬')!=-1 or x.find('大神')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'游戏主美' if (x.find('游戏')!=-1 or x.find('手游')!=-1)and(x.find('场景')!=-1 or x.find('界面')!=-1 or x.find('主美')!=-1 or x.find('美术')!=-1 or x.find('原画')!=-1 or x.find('动画')!=-1 or x.find('动漫')!=-1) else x)
    df['职位']=df.职位.apply(lambda x:'游戏商务GS引导员GM' if (x.find('游戏')!=-1 or x.find('手游')!=-1)and(x.find('商务')!=-1 or x.find('GS')!=-1 or x.find('投放')!=-1 or x.find('引导')!=-1 or x.find('业务')!=-1 or x.find('营销')!=-1 or x.find('gm')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'游戏开发工程师' if (x.find('游戏')!=-1 or x.find('手游')!=-1)and x.find('服务端')==-1 and x.find('客户端')==-1 and(x.find('开发')!=-1 or x.find('制作')!=-1 or x.find('研发')!=-1 or x.find('工程')!=-1 or x.find('SDK')!=-1 or x.find('sdk')!=-1 or x.find('程序')!=-1)or x.find('U3D')!=-1 or x.find('u3d')!=-1 or x.find('nity3')!=-1 else x)

    df['职位']=df.职位.apply(lambda x:'英语客服' if x.find('英语')!=-1 and x.find('客服')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'英语班主任' if x.find('英语')!=-1 and x.find('班主任')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'英语课程顾问' if x.find('英语')!=-1 and x.find('课程顾问')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'英语翻译' if x.find('英语翻译')!=-1 else x)

    df['职位']=df.职位.apply(lambda x:'软测实习生' if (x.find('测试')!=-1 or x.find('软测')!=-1)and(x.find('实习')!=-1 or x.find('实训')!=-1 or x.find('学徒')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'软测管理岗位' if (x.find('测试')!=-1 or x.find('软测')!=-1)and(x.find('经理')!=-1 or x.find('主管')!=-1 or x.find('总监')!=-1 or x.find('leader')!=-1 or x.find('组长')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'硬件测试' if x.find('硬件')!=-1 and x.find('测试')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'自动化测试' if x.find('自动化')!=-1 and x.find('测试')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'软件测试工程师' if (x.find('测试')!=-1 or x.find('软测')!=-1)and x.find('实习')==-1 and x.find('管理')==-1 and x.find('硬件')==-1 and x.find('自动化')==-1 else x)

    df['职位']=df.职位.apply(lambda x:'新媒体运营' if x.find('运营')!=-1 and(x.find('媒体')!=-1 or x.find('号')!=-1 or x.find('直播')!=-1 or x.find('主播')!=-1 or x.find('短视频')!=-1 or x.find('微博')!=-1 or x.find('微信')!=-1 or x.find('网红')!=-1 or x.find('acebook')!=-1 or x.find('UGC')!=-1 or x.find('PR')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'电商运营' if x.find('运营')!=-1 and(x.find('电商')!=-1 or x.find('亚马逊')!=-1 or x.find('天猫')!=-1 or x.find('淘宝')!=-1 or x.find('京东')!=-1 or x.find('速卖通')!=-1 or x.find('Ebay')!=-1 or x.find('mazon')!=-1 or x.find('唯品')!=-1 or x.find('日本站')!=-1 or x.find('国际站')!=-1 or x.find('自建站')!=-1 or x.find('独立站')!=-1 or x.find('拼团')!=-1 
    or x.find('微商')!=-1 or x.find('网店')!=-1 or x.find('沃尔玛')!=-1 or x.find('拼多多')!=-1 or x.find('商家')!=-1 or x.find('阿里巴巴')!=-1 or x.find('海外')!=-1 or x.find('销售')!=-1 or x.find('营销')!=-1 or x.find('商城')!=-1 or x.find('渠道')!=-1 or x.find('shopify')!=-1 or x.find('CRM')!=-1 or x.find('店')!=-1 or x.find('商务')!=-1 or x.find('AMAZON')!=-1 or x.find('SOUQ')!=-1 
    or x.find('外贸')!=-1 or x.find('1688')!=-1 or x.find('商品')!=-1 or x.find('eBay')!=-1 or x.find('Shopee')!=-1 or x.find('B端')!=-1 or x.find('wish')!=-1 or x.find('有赞')!=-1 or x.find('口碑')!=-1 or x.find('OTA')!=-1 or x.find('德')!=-1 or x.find('法')!=-1 or x.find('西')!=-1 or x.find('意')!=-1 or x.find('日')!=-1 or x.find('英')!=-1 or x.find('荷兰')!=-1 or x.find('SEM')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'产品运营' if x.find('运营专员')!=-1 or x.find('运营助理')!=-1 or x.find('运营总监')!=-1 or x.find('运营经理')!=-1 or x.find('产品运营')!=-1 or x.find('运营主管')!=-1 or x.find('网络运营')!=-1 or x.find('平台运营')!=-1 or x.find('抖音运营')!=-1 or x.find('程序运营')!=-1 
    or x.find('小红书运营')!=-1 or x.find('线上运营')!=-1 or x.find('项目运营')!=-1 or x.find('APP运营')!=-1 or x.find('高级运营')!=-1 or x.find('维护运营')!=-1 or x.find('资深运营')!=-1 or x.find('互联网后台')!=-1 or x.find('管培生')!=-1 or x.find('百度运营')!=-1 or x.find('SP运营')!=-1 or x.find('互联网运营')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'品类类目运营' if x.find('运营')!=-1 and (x.find('类目')!=-1 or x.find('品类')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'内容活动运营' if x.find('内容运营')!=-1 or x.find('活动运营')!=-1 or x.find('运营策划')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'游戏运营' if x.find('游戏运营')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'数据运营' if x.find('数据运营')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'视频运营' if x.find('运营')!=-1 and x.find('视频')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'课程运营' if x.find('运营')!=-1 and x.find('课程')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'设计师运营' if x.find('运营')!=-1 and x.find('设计师')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'广告运营' if x.find('运营')!=-1 and (x.find('广告')!=-1 or x.find('浏览器新闻')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'运营实习生' if x.find('运营实习生')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'用户社群运营运营' if x.find('运营')!=-1 and(x.find('社区')!=-1 or x.find('社群')!=-1 or x.find('用户')!=-1 or x.find('C端')!=-1 or x.find('客服')!=-1 or x.find('VIP')!=-1)else x)

    df['职位']=df.职位.apply(lambda x:'电商客服' if x.find('客服')!=-1 and(x.find('电商')!=-1 or x.find('淘宝')!=-1 or x.find('天猫')!=-1 or x.find('bay')!=-1 or x.find('亚马逊')!=-1 or x.find('阿里巴巴')!=-1 or x.find('网店')!=-1 or x.find('外贸')!=-1 
    or x.find('飞猪')!=-1 or x.find('支付宝')!=-1 or x.find('EBAY')!=-1 or x.find('速卖通')!=-1 or x.find('华硕')!=-1 or x.find('Shopee')!=-1 or x.find('商业')!=-1 or x.find('电话')!=-1 or x.find('接听')!=-1 or x.find('VIP')!=-1 or x.find('OTA')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'网络在线客服' if x.find('客服')!=-1 and(x.find('网')!=-1 or x.find('线')!=-1 or x.find('专员')!=-1 or x.find('软件')!=-1 or x.find('技术')!=-1 or x.find('IT')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'微信客服' if x.find('客服')!=-1 and x.find('微信')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'售后客服' if x.find('客服')!=-1 and x.find('售后')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'客服助理' if x.find('客服')!=-1 and x.find('助理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'客服经理' if x.find('客服')!=-1 and (x.find('经理')!=-1 or x.find('主管')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'小语种客服' if x.find('客服')!=-1 and (x.find('粤')!=-1 or x.find('德')!=-1 or x.find('英')!=-1 or x.find('日')!=-1 )else x)

    df['职位']=df.职位.apply(lambda x:'网络信息安全' if x.find('安全')!=-1 and (x.find('网络')!=-1 or x.find('信息')!=-1 or x.find('eb')!=-1 or x.find('系统')!=-1 or x.find('开发')!=-1 or x.find('EB')!=-1 or x.find('服务')!=-1 or x.find('研发')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'网络运维' if x.find('网络')!=-1 and (x.find('运维')!=-1 or x.find('维护')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'网络管理员' if (x.find('网络')!=-1 and x.find('管理')!=-1) or x.find('网管')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网络架构师' if (x.find('网络')!=-1 or x.find('互联网')!=-1)and x.find('架构')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网络游戏' if x.find('网络')!=-1 and x.find('游戏')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网络营销' if x.find('网络')!=-1 and x.find('营销')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网络主管' if x.find('网络')!=-1 and (x.find('主管')!=-1 or x.find('经理')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'网络工程师' if x.find('网络')!=-1 and (x.find('工程')!=-1 or x.find('技术')!=-1 or x.find('Network')!=-1)else x)

    df['职位']=df.职位.apply(lambda x:'网站设计' if x.find('网站设计')!=-1 or x.find('网站策划')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网站运维' if (x.find('网站')!=-1 or x.find('网页')!=-1 )and (x.find('运营')!=-1 or x.find('维护')!=-1 or x.find('运维')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'网站运营' if x.find('网站运营')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网站开发' if (x.find('网站')!=-1 or x.find('网页')!=-1 )and (x.find('开发')!=-1 or x.find('程序')!=-1 or x.find('建设')!=-1 or x.find('工程')!=-1 or x.find('优化')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'网页设计' if x.find('网页')!=-1 and(x.find('设计')!=-1 or x.find('制作')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'网店店长' if x.find('网')!=-1 and x.find('店长')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'网络销售' if x.find('网销')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'互联网开发' if x.find('互联网')!=-1 and (x.find('开发')!=-1 or x.find('研发')!=-1 or x.find('技术')!=-1 or x.find('软件')!=-1 )else x)

    df['职位']=df.职位.apply(lambda x:'C++实习' if (x.find('C++')!=-1 or x.find('c++')!=-1)and x.find('实习')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'C++研发工程师' if (x.find('C++')!=-1 or x.find('c++')!=-1)and x.find('研发')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'C++开发工程师' if (x.find('C++')!=-1 or x.find('c++')!=-1)and x.find('实习')==-1 and x.find('研发')==-1 else x)

    df['职位']=df.职位.apply(lambda x:'VR开发工程师' if x.find('VR')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'系统架构师' if x.find('系统架构')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'后端架构师' if x.find('架构')!=-1 and (x.find('后')!=-1 or x.find('服务')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'软件架构师' if x.find('架构')!=-1 and x.find('软件')!=-1 else x)

    df['职位']=df.职位.apply(lambda x:'APP开发工程师' if (x.find('APP')!=-1 or x.find('app')!=-1) and (x.find('开发')!=-1 or x.find('研发')!=-1) else x)
    df['职位']=df.职位.apply(lambda x:'Ruby开发工程师' if x.find('uby')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'物联网开发' if x.find('物联网')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'嵌入式算法工程师' if x.find('嵌入式')!=-1 and x.find('算法')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'嵌入式系统工程师' if x.find('嵌入式')!=-1 and x.find('系统')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'嵌入式应用工程师' if x.find('嵌入式')!=-1 and x.find('应用')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'嵌入式软件开发' if x.find('嵌入式')!=-1 and (x.find('软件')!=-1 or x.find('开发')!=-1) else x)
    df['职位']=df.职位.apply(lambda x:'硬件研发' if x.find('硬件')!=-1 and x.find('研发')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'硬件测试' if x.find('硬件')!=-1 and x.find('测试')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'硬件维护' if x.find('硬件')!=-1 and x.find('维护')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'硬件工程师' if x.find('硬件')!=-1 and (x.find('工程')!=-1 or x.find('计算机')!=-1 or x.find('技术')!=-1 ) else x)

    df['职位']=df.职位.apply(lambda x:'ERP实施' if x.find('实施')!=-1 and x.find('ERP')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'SAP实施' if x.find('实施')!=-1 and x.find('SAP')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'实施经理' if x.find('实施')!=-1 and x.find('经理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'项目实施' if x.find('实施')!=-1 and x.find('项目')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'实施顾问' if x.find('实施')!=-1 and x.find('顾问')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'软件实施工程师' if x.find('AI')==-1 and x.find('大数据')==-1 and x.find('.NET')==-1 and x.find('ERP')==-1 and x.find('SAP')==-1 and x.find('经理')==-1 and x.find('项目')==-1 and x.find('顾问')==-1 and x.find('实施')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'H5开发工程师' if x.find('H5')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'IT专员' if x.find('IT专员')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'IT经理' if x.find('IT经理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'IT主管' if x.find('IT')!=-1 and x.find('主管')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'IT实习生' if x.find('IT')!=-1 and (x.find('实习')!=-1 or x.find('ntern')!=-1) else x)
    df['职位']=df.职位.apply(lambda x:'IT支持工程师' if x.find('IT')!=-1 and (x.find('支持')!=-1 or x.find('支撑')!=-1) else x)
    df['职位']=df.职位.apply(lambda x:'系统工程师' if x.find('IT')!=-1 and x.find('系统')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'桌面运维' if (x.find('IT')!=-1 and (x.find('维')!=-1 or x.find('桌面')!=-1))or x.find('桌面运维')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'IT工程师' if x.find('IT工程师')!=-1 or x.find('IT软件工程师')!=-1 or x.find('ITEngineer')!=-1 or x.find('IT岗')!=-1 or x.find('转行IT')!=-1 else x)

    df['职位']=df.职位.apply(lambda x:'研发经理' if x.find('研发')!=-1 and x.find('经理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'研发助理' if x.find('研发')!=-1 and x.find('助理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'软件研发工程师' if (x.find('研发')!=-1 and x.find('软件')!=-1) or x.find('研发工程师')==0 else x)
    df['职位']=df.职位.apply(lambda x:'后台研发工程师' if x.find('研发')!=-1 and x.find('后')!=-1 else x)

    df['职位']=df.职位.apply(lambda x:'ABAP/SAP研发' if (x.find('ABAP')!=-1 or x.find('SAP')!=-1)and x.find('研发')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'ABAP/SAP开发' if (x.find('ABAP')!=-1 or x.find('SAP')!=-1)and(x.find('开发')!=-1 or x.find('工程')!=-1) else x)
    df['职位']=df.职位.apply(lambda x:'ABAP/SAP助理' if (x.find('ABAP')!=-1 or x.find('SAP')!=-1)and(x.find('onsultant')!=-1 or x.find('助理')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'微信小程序开发' if x.find('小程序')!=-1 and x.find('开发')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'SEO主管/经理' if x.find('SEO')!=-1 and (x.find('主管')!=-1 or x.find('经理')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'SEO实习' if x.find('SEO')!=-1 and x.find('实习')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'SEO分析师' if x.find('SEO')!=-1 and x.find('分析')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'SEO搜索引擎优化' if (x.find('SEO')!=-1 and (x.find('优化')!=-1 or x.find('工程')!=-1))or x.find('诚聘SEO')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'SEO专员' if x.find('SEO')!=-1 and x.find('专员')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'搜索引擎工程师' if x.find('搜索引擎')!=-1 and x.find('工程')!=-1 else x)

    df['职位']=df.职位.apply(lambda x:'服务器运维' if x.find('服务器')!=-1 and x.find('运维')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'服务器开发' if x.find('Java')==-1 and x.find('服务器')!=-1 and x.find('开发')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'后端开发工程师' if x.find('web')==-1 and x.find('后端')!=-1 and (x.find('开发')!=-1 or x.find('程序')!=-1 or x.find('工程')!=-1 )else x)
    df['职位']=df.职位.apply(lambda x:'全栈工程师' if x.find('全栈')!=-1 and x.find('PHP')==-1  and x.find('Java')==-1 and x.find('web')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'交互设计师' if x.find('交互设计师')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'交互设计助理' if x.find('交互设计助理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'交互设计实习' if x.find('交互设计实习')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'执行专员' if x.find('执行专员')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'执行策划' if x.find('执行策划')!=-1 else x)

    df['职位']=df.职位.apply(lambda x:'电商专员' if (x.find('电商')!=-1 or x.find('电子商务')!=-1)and x.find('专员')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'电商经理' if (x.find('电商')!=-1 or x.find('电子商务')!=-1)and(x.find('经理')!=-1 or x.find('主管')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'电商助理' if (x.find('电商')!=-1 or x.find('电子商务')!=-1)and x.find('助理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'电商设计师' if x.find('电商')!=-1 and x.find('设计')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'电商实习生' if (x.find('电商')!=-1 or x.find('电子商务')!=-1)and x.find('实习')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'广告优化师' if x.find('广告优化')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'广告投放优化' if x.find('投放')!=-1 and (x.find('优化')!=-1 or x.find('师')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'广告投放主管/经理' if x.find('投放')!=-1 and (x.find('主管')!=-1 or x.find('经理')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'广告投放实习' if x.find('投放')!=-1 and x.find('生')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'广告投放专员' if x.find('投放')!=-1 and x.find('优化')==-1 and x.find('主管')==-1 and x.find('实习')==-1 else x)

    df['职位']=df.职位.apply(lambda x:'QT开发工程师' if x.find('QT')!=-1 or x.find('qt')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'AS3开发工程师' if x.find('AS3')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Erlang开发工程师' if x.find('Erlang')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'ATM维护工程师' if x.find('ATM')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'LTE工程师' if x.find('LTE')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'软件工程师' if x.find('软件工程师')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'软件开发' if x.find('软件开发')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'软件实习生' if x.find('软件')!=-1 and (x.find('实习')!=-1 or x.find('学徒')!=-1) else x)

    df['职位']=df.职位.apply(lambda x:'系统运维' if x.find('系统运维')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'运维实习生' if x.find('运维')!=-1 and x.find('实习')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'运维助理' if x.find('运维')!=-1 and x.find('助理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'运维主管/经理' if x.find('运维')!=-1 and(x.find('主管')!=-1 or x.find('总监')!=-1 or x.find('经理')!=-1 or x.find('leader')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'机房运维' if x.find('运维')!=-1 and x.find('机房')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'IDC运维' if x.find('运维')!=-1 and x.find('IDC')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'ERP运维' if x.find('运维')!=-1 and x.find('ERP')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'运维工程师' if x.find('运维工程师')!=-1 or x.find('运维开发')!=-1 else x)

    df['职位']=df.职位.apply(lambda x:'技术总监' if x.find('技术')!=-1 and x.find('总监')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'技术经理' if x.find('技术')!=-1 and x.find('经理')!=-1 and x.find('Java')==-1 and x.find('Python')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'项目助理' if x.find('项目')!=-1 and x.find('助理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'售后工程师' if x.find('售后')!=-1 and(x.find('工程师')!=-1 or x.find('支持')!=-1)else x)
    df['职位']=df.职位.apply(lambda x:'系统工程师' if x.find('系统工程师')!=-1 and x.find('嵌入式系统工程师')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'系统策划师' if x.find('系统策划')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'系统集成工程师' if x.find('系统集成工程师')!=-1 else x)

    df['职位']=df.职位.apply(lambda x:'外贸业务员' if x.find('外贸')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'微信公众号运营' if x.find('公众号')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'插画设计师' if x.find('插画')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'Lua开发工程师' if x.find('Lua')!=-1 or x.find('lua')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'界面设计师' if x.find('界面')!=-1 and x.find('设计')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'单片机开发工程师' if x.find('单片机')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'媒介专员' if x.find('媒介')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'UPS工程师' if x.find('UPS')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'UED_leader' if x.find('UED')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'云平台工程师' if x.find('云平台')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'品牌策划' if x.find('品牌')!=-1 and x.find('策划')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'战略分析' if x.find('战略')!=-1 and x.find('分析')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'SEM主管' if x.find('SEM')!=-1 and(x.find('主管')!=-1 or x.find('总监')!=-1 or x.find('经理')!=-1) else x)
    df['职位']=df.职位.apply(lambda x:'SEM优化师' if x.find('SEM')!=-1 and x.find('优化')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'SEM专员' if x.find('SEM')!=-1 and x.find('优化')==-1 and x.find('主管')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'ASO专员' if x.find('ASO')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'机房维护' if x.find('机房')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'客户经理' if x.find('客户经理')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'新媒体专员' if x.find('新媒体')!=-1 and x.find('专员')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'报表开发工程师' if x.find('报表')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'现场工程师' if x.find('现场')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'竞价专员' if x.find('竞价')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'多媒体开发工程师' if x.find('多媒体')!=-1 and x.find('发')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'多媒体设计师' if x.find('多媒体')!=-1 and x.find('设计')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'存储工程师' if x.find('存储')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'架构师' if x.find('架构')!=-1 and x.find('Web')==-1 and x.find('Java')==-1  and x.find('PHP')==-1 and x.find('大数据')==-1 and x.find('C#')==-1 and x.find('Android')==-1 and x.find('网络')==-1 and x.find('系统')==-1 and x.find('后端')==-1 and x.find('软件')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'音视频开发工程师' if x.find('音视频')!=-1 and x.find('算法')==-1 else x)
    df['职位']=df.职位.apply(lambda x:'SRE工程师' if x.find('SRE')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:'System Engineer' if x.find('ystem')!=-1 else x)
    # 删除括号 最多可以删除三个括号
    df['职位']=df.职位.apply(lambda x:x[:x.find('（')]+x[x.find('）')+1:] if x.find('（')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:x[:x.find('（')]+x[x.find('）')+1:] if x.find('（')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:x[:x.find('（')]+x[x.find('）')+1:] if x.find('（')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:x[:x.find('(')]+x[x.find(')')+1:] if x.find('(')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:x[:x.find('(')]+x[x.find(')')+1:] if x.find('(')!=-1 else x)
    df['职位']=df.职位.apply(lambda x:x[:x.find('(')]+x[x.find(')')+1:] if x.find('(')!=-1 else x)


def to_file(df, filename):
    df.to_csv(filename, index=False)


if __name__ == '__main__':
    df = read_file('final.csv')
    describe(df)
    clean(df)
    to_file(df, 'new.csv')
    describe(df)
